import { itemReward } from '../reward/ItemReward';
import { Cutscene } from './Cutscene';

export const CUTSCENES: Record<string, Cutscene> = {
  narration_ancient_pulse: new Cutscene('narration_ancient_pulse', 'dialog:narration_ancient_pulse', undefined, { 1: 'images/items/ancient_statue.png', 2: '' }, {
    3: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
    4: { speakerKey: 'pilots:dr_thrun', portrait: 'images/pilots/dr_thrun.png' },
    5: { speakerKey: 'pilots:dr_thrun', portrait: 'images/pilots/dr_thrun.png' },
  }),
  narration_arcobaleno_plan: new Cutscene('narration_arcobaleno_plan', 'dialog:narration_arcobaleno_plan', undefined, {1: 'images/cutscenes/arcobaleno.jpg'}),
  narration_beacon_emerges: new Cutscene('narration_beacon_emerges', 'dialog:narration_beacon_emerges', undefined, { 0: 'images/cutscenes/tortoise_desert.png', 3: 'images/characters/beacon_full.png', 5: '', 7: 'images/characters/beacon_full.png' }, {
    4: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    5: { speakerKey: '', portrait: '' },
    8: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    9: { speakerKey: '', portrait: '' },
    10: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
  }),
  narration_bandits_flee: new Cutscene('narration_bandits_flee', 'dialog:narration_bandits_flee', undefined, {0: 'images/cutscenes/rosso_defeat.jpg'}),
  narration_colony_attack: new Cutscene('narration_colony_attack', 'dialog:narration_colony_attack', undefined, {0: 'images/cutscenes/colony_attack.jpg'}),
  narration_porto_nido_attack: new Cutscene('narration_porto_nido_attack', 'dialog:narration_porto_nido_attack', undefined, undefined, {
    1: { speakerKey: 'pilots:arcadia_guard', portrait: 'images/pilots/arcadia_guard.png' },
    2: { speakerKey: '', portrait: '' },
    3: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    4: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    5: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
    6: { speakerKey: 'pilots:raven', portrait: 'images/pilots/raven.png' },
  }),
  narration_raven_aftermath: new Cutscene('narration_raven_aftermath', 'dialog:narration_raven_aftermath', undefined, undefined, {
    0: { speakerKey: 'pilots:raven', portrait: 'images/pilots/raven.png' },
    1: { speakerKey: 'pilots:raven', portrait: 'images/pilots/raven.png' },
  }),
  narration_officer_deal_imperial: new Cutscene('narration_officer_deal_imperial', 'dialog:narration_officer_deal_imperial', undefined, undefined, {
    0: { speakerKey: '', portrait: '' },
    1: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    2: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    3: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    4: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    5: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    6: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    7: { speakerKey: '', portrait: '' },
  }),
  narration_officer_deal_neutral: new Cutscene('narration_officer_deal_neutral', 'dialog:narration_officer_deal_neutral', undefined, undefined, {
    0: { speakerKey: '', portrait: '' },
    1: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    2: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    3: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    4: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    5: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    6: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    7: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    8: { speakerKey: '', portrait: '' },
  }),
  narration_officer_deal_republican: new Cutscene('narration_officer_deal_republican', 'dialog:narration_officer_deal_republican', undefined, undefined, {
    0: { speakerKey: '', portrait: '' },
    1: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    2: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    3: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    4: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    5: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    6: { speakerKey: 'pilots:republican_officer', portrait: 'images/pilots/republican_officer.png' },
    7: { speakerKey: '', portrait: '' },
  }),
  narration_gale_ew: new Cutscene('narration_gale_ew', 'dialog:narration_gale_ew', undefined, undefined, {
    0: { speakerKey: 'pilots:gale_task', portrait: 'images/pilots/gale_task.png' },
  }),
  narration_gorge_ambush: new Cutscene('narration_gorge_ambush', 'dialog:narration_gorge_ambush', undefined, { 3: 'images/cutscenes/ancient_beat.gif', 4: '' }, {
    1: { speakerKey: 'pilots:gale_task', portrait: 'images/pilots/gale_task.png' },
    2: { speakerKey: 'pilots:opis_kerone', portrait: 'images/pilots/opis.png' },
    3: { speakerKey: '', portrait: '' },
    5: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    6: { speakerKey: '', portrait: '' },
    7: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    8: { speakerKey: 'pilots:opis_kerone', portrait: 'images/pilots/opis.png' },
    9: { speakerKey: '', portrait: '' },
    10: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    11: { speakerKey: '', portrait: '' },
    13: { speakerKey: 'pilots:gale_task', portrait: 'images/pilots/gale_task.png' },
    14: { speakerKey: 'pilots:opis_kerone', portrait: 'images/pilots/opis.png' },
  }),
  narration_gorge_retreat: new Cutscene('narration_gorge_retreat', 'dialog:narration_gorge_retreat', undefined, undefined, {
    1: { speakerKey: 'pilots:gale_task', portrait: 'images/pilots/gale_task.png' },
    2: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    3: { speakerKey: 'pilots:opis_kerone', portrait: 'images/pilots/opis.png' },
    4: { speakerKey: '', portrait: '' },
    5: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    6: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
    7: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
  }),
  narration_gorge_tortoise: new Cutscene('narration_gorge_tortoise', 'dialog:narration_gorge_tortoise', undefined, { 2: 'images/zoids/cannon_tortoise_os.png', 4: 'images/zoids/ancient_tortoise.png', 5: '' }, {
    0: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    1: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
    2: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    3: { speakerKey: '', portrait: '' },
    4: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    5: { speakerKey: 'pilots:opis_kerone', portrait: 'images/pilots/opis.png' },
    6: { speakerKey: 'pilots:opis_kerone', portrait: 'images/pilots/opis.png' },
  }),
  narration_tortoise_reborn: new Cutscene('narration_tortoise_reborn', 'dialog:narration_tortoise_reborn', undefined, { 8: 'images/cutscenes/tortoise_evo_start.gif', 9: 'images/cutscenes/cocoon_shoot.gif', 10: 'images/cutscenes/tortoise_evo_end.gif', 11: '', 14: 'images/zoids/barrage_tortoise.png', 15: '' }, {
    1: { speakerKey: 'pilots:gale_task', portrait: 'images/pilots/gale_task.png' },
    2: { speakerKey: '', portrait: '' },
    4: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
    5: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
    6: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    7: { speakerKey: '', portrait: '' },
    11: { speakerKey: 'pilots:gale_task', portrait: 'images/pilots/gale_task.png' },
    12: { speakerKey: 'pilots:opis_kerone', portrait: 'images/pilots/opis.png' },
    13: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
    14: { speakerKey: '', portrait: '' },
    15: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    16: { speakerKey: 'pilots:gale_task', portrait: 'images/pilots/gale_task.png' },
  }),
  narration_dr_t_appears: new Cutscene('narration_dr_t_appears', 'dialog:narration_dr_t_appears', undefined, undefined, { 1: { portrait: 'images/pilots/dr_t.png', speakerKey: '???' }, 2: {portrait: '', speakerKey: ''} }),
  narration_discover_fione: new Cutscene('narration_discover_fione', 'dialog:narration_discover_fione', itemReward('ancient_statue', 1, true), { 1: 'images/cutscenes/fine_ruins.jpg', 2: 'images/items/ancient_statue.png' }),
  narration_kara_imperial_camp: new Cutscene('narration_kara_imperial_camp', 'dialog:narration_kara_imperial_camp', undefined, undefined, {
    0: { speakerKey: 'pilots:imperial_registration_officer', portrait: 'images/pilots/empire_soldier.png' },
    1: { speakerKey: 'pilots:imperial_registration_officer', portrait: 'images/pilots/empire_soldier.png' },
    2: { speakerKey: 'pilots:imperial_registration_officer', portrait: 'images/pilots/empire_soldier.png' },
    3: { speakerKey: 'pilots:imperial_registration_officer', portrait: 'images/pilots/empire_soldier.png' },
    4: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
  }),
  narration_maria_kidnapped: new Cutscene('narration_maria_kidnapped', 'dialog:narration_maria_kidnapped', undefined, {0: 'images/cutscenes/maria_kidnap.jpg'}),
  narration_stray_helcat: new Cutscene('narration_stray_helcat', 'dialog:narration_stray_helcat', undefined, undefined, {
    1: { speakerKey: 'pilots:dr_thrun', portrait: 'images/pilots/dr_thrun.png' },
    6: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    7: { speakerKey: 'pilots:dr_thrun', portrait: 'images/pilots/dr_thrun.png' },
  }),
  narration_stray_gets_up: new Cutscene('narration_stray_gets_up', 'dialog:narration_stray_gets_up', undefined, undefined, {
    1: { speakerKey: 'pilots:dr_thrun', portrait: 'images/pilots/dr_thrun.png' },
  }),
  narration_republican_intervention: new Cutscene('narration_republican_intervention', 'dialog:narration_republican_intervention', undefined, undefined, {
    1: { speakerKey: 'pilots:unia_corin', portrait: 'images/pilots/unia.png' },
    2: { speakerKey: 'pilots:dr_t', portrait: 'images/pilots/dr_t.png' },
  }),
  narration_shield_liger: new Cutscene('narration_shield_liger', 'dialog:narration_shield_liger', undefined, {0: 'images/cutscenes/van_zeke_escape.jpg',1:'images/cutscenes/shield_liger.jpg'}),
  narration_tortoise_appears: new Cutscene('narration_tortoise_appears', 'dialog:narration_tortoise_appears', undefined, { 0: 'images/cutscenes/tortoise_desert.png' }, {
    1: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
    2: { speakerKey: 'pilots:kara', portrait: 'images/pilots/girl.png' },
  }),
  narration_turtle_savior: new Cutscene('narration_turtle_savior', 'dialog:narration_turtle_savior', undefined, {0: 'images/cutscenes/red_horn.jpg', 1: 'images/items/ancient_statue.png', 2: 'images/cutscenes/red_horn_shoot.jpg', 3: 'images/cutscenes/turtle_shot.jpg'}),
  narration_van_farewell: new Cutscene('narration_van_farewell', 'dialog:narration_van_farewell', undefined, {0: 'images/cutscenes/van_farewell.jpg'}),
};
