import { AllOfRule, AtLeastOneOfRule, AttackRule, Evolution, FactionRule, HealthRule, ItemRule, LevelRule } from '../evolution';
import { ItemDrop } from '../item/ItemDrop';
import { ZiDataDrop } from '../item/ZiDataDrop';
import { Faction } from './Faction';
import { LevelType } from './LevelType';
import { TerrainType } from './Terrain';
import type { ZoidSpecies } from './ZoidSpecies';
import { ZoidSize } from './ZoidSpecies';

export const ZOID_LIST: Record<string, ZoidSpecies> = {
  ancient_tortoise: {
    id: 'ancient_tortoise',
    name: 'Ancient Tortoise',
    attack: 180,
    maxHealth: 600,
    baseExp: 60,
    coreFragments: 1300,
    faction: Faction.Neutral,
    levelType: LevelType.Slow,
    price: 15000,
    scanRate: -1,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 5.8,
    length: 11.3,
    speed: 60,
    type: 'tortoise',
    weight: 40.1,
    width: 6.3,
  },
  aquadon: {
    id: 'aquadon',
    name: 'Aquadon',
    attack: 100,
    maxHealth: 80,
    baseExp: 50,
    coreFragments: 400,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 2000,
    scanRate: 65,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Water],
    evolutions: [new Evolution('furolesios', new LevelRule(50))],
    height: 2.7,
    length: 9.8,
    speed: 80,
    type: 'frog',
    weight: 5.9,
    width: 6,
  },
  barigator: {
    id: 'barigator',
    name: 'Barigator',
    attack: 160,
    maxHealth: 350,
    baseExp: 50,
    coreFragments: 1600,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 30000,
    scanRate: 35,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 4.4,
    length: 14.5,
    speed: 150,
    type: 'crocodile',
    weight: 24.3,
    width: 4,
  },
  barrage_tortoise: {
    id: 'barrage_tortoise',
    name: 'Barrage Tortoise',
    attack: 210,
    maxHealth: 1000,
    baseExp: 150,
    coreFragments: 1500,
    faction: Faction.Neutral,
    levelType: LevelType.MediumFast,
    price: 200000,
    scanRate: -1,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 6.8,
    length: 9.9,
    speed: 120,
    type: 'turtle',
    weight: 43.1,
    width: 6.3,
  },
  bear_fighter: {
    id: 'bear_fighter',
    name: 'Bear Fighter',
    attack: 220,
    maxHealth: 500,
    baseExp: 80,
    coreFragments: 1800,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 40000,
    scanRate: 35,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 6.8,
    length: 12,
    speed: 190,
    type: 'bear',
    weight: 45.6,
    width: 6.3,
  },
  cannon_tortoise: {
    id: 'cannon_tortoise',
    name: 'Cannon Tortoise',
    attack: 160,
    maxHealth: 500,
    baseExp: 50,
    coreFragments: 1300,
    evolutions: [new Evolution('cannon_tortoise_bc', new ItemRule('buster_cannon'))],
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 8000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 5.8,
    length: 9.9,
    speed: 100,
    type: 'turtle',
    weight: 33.6,
    width: 6.3,
  },
  cannon_tortoise_bc: {
    id: 'cannon_tortoise_bc',
    name: 'Cannon Tortoise BC',
    attack: 230,
    maxHealth: 700,
    baseExp: 80,
    coreFragments: 1500,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 0,
    scanRate: 30,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    itemDrops: [new ItemDrop('buster_cannon', 10)],
    height: 5.8,
    length: 9.9,
    speed: 80,
    type: 'turtle',
    weight: 38.3,
    width: 6.3,
  },
  cannon_tortoise_os: {
    id: 'cannon_tortoise_os',
    name: 'Cannon Tortoise OS',
    attack: 200,
    maxHealth: 800,
    baseExp: 100,
    coreFragments: 2000,
    faction: Faction.Neutral,
    levelType: LevelType.Slow,
    price: 50000,
    scanRate: -1,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 5.8,
    length: 9.9,
    speed: 100,
    type: 'turtle',
    weight: 40.3,
    width: 6.3,
  },
  command_wolf: {
    id: 'command_wolf',
    name: 'Command Wolf',
    attack: 200,
    maxHealth: 250,
    baseExp: 50,
    coreFragments: 1600,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 35000,
    scanRate: 35,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 7.9,
    length: 14.7,
    speed: 200,
    type: 'wolf',
    weight: 46,
    width: 5.9,
  },
  command_wolf_desert: {
    id: 'command_wolf_desert',
    name: 'Command Wolf (Desert)',
    attack: 200,
    maxHealth: 250,
    baseExp: 50,
    coreFragments: 1600,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 35000,
    scanRate: 35,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 7.9,
    length: 14.7,
    speed: 200,
    type: 'wolf',
    weight: 46,
    width: 5.9,
  },
  crablaster: {
    id: 'crablaster',
    name: 'Crablaster',
    attack: 50,
    maxHealth: 140,
    baseExp: 20,
    coreFragments: 400,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.Fast,
    price: 2500,
    scanRate: 75,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 3.0,
    length: 2.8,
    speed: 100,
    type: 'crab',
    weight: 3.8,
  },
  crosswinger: {
    id: 'crosswinger',
    name: 'Crosswinger',
    attack: 70,
    maxHealth: 100,
    baseExp: 30,
    coreFragments: 800,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 5000,
    scanRate: 70,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Air],
    height: 1.5,
    length: 5.9,
    speed: 1111,
    type: 'dragonfly',
    weight: 2.5,
  },
  dcsj: {
    id: 'dcsj',
    name: 'Shield Liger DCS-J',
    attack: 320,
    maxHealth: 600,
    baseExp: 150,
    coreFragments: 2500,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Slow,
    price: 150000,
    scanRate: 20,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 11.5,
    length: 21.6,
    speed: 285,
    type: 'lion',
    weight: 115,
  },
  dragon_horse: {
    id: 'dragon_horse',
    name: 'Dragon Horse',
    attack: 20,
    maxHealth: 70,
    baseExp: 20,
    coreFragments: 250,
    faction: Faction.Neutral,
    levelType: LevelType.Erratic,
    price: 1000,
    scanRate: 50,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Land],
  },
  double_sworder: {
    id: 'double_sworder',
    name: 'Double Sworder',
    attack: 190,
    maxHealth: 180,
    baseExp: 50,
    coreFragments: 1000,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 35000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Air, TerrainType.Land],
    height: 3.96,
    length: 11.6,
    speed: 415,
    type: 'insect',
    weight: 19.7,
    width: 9.72,
  },
  elephantus: {
    id: 'elephantus',
    name: 'Elephantus',
    attack: 100,
    maxHealth: 200,
    baseExp: 80,
    coreFragments: 2000,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumSlow,
    price: 20000,
    scanRate: 30,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    evolutions: [
      new Evolution('mammoth', new HealthRule(500)),
      new Evolution('twinhorn', new AllOfRule([
        new HealthRule(400),
        new AtLeastOneOfRule([
          new FactionRule(Faction.GuylosEmpire),
          new FactionRule(Faction.ZenebasEmpire),
        ]),
      ])),
    ],
    height: 4,
    length: 8.3,
    speed: 95,
    type: 'elephant',
    weight: 17.7,
    width: 5.1,
  },
  furolesios: {
    id: 'furolesios',
    name: 'Furolesios',
    attack: 200,
    maxHealth: 200,
    baseExp: 80,
    coreFragments: 1600,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 20000,
    scanRate: -1,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 7.1,
    length: 13,
    speed: 83,
    type: 'sea_dragon',
    weight: 8.85,
    width: 9,
  },
  garius: {
    id: 'garius',
    name: 'Garius',
    attack: 50,
    maxHealth: 100,
    baseExp: 50,
    coreFragments: 1000,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 4000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    evolutions: [
      new Evolution('godos', new LevelRule(50)),
      new Evolution('iguan', new AllOfRule([
        new LevelRule(50),
        new FactionRule(Faction.GuylosEmpire),
      ])),
    ],
    height: 7.8,
    length: 6.5,
    speed: 270,
    type: 'dinosaur',
    weight: 12.5,
    width: 3.5,
  },
  gator: {
    id: 'gator',
    name: 'Gator',
    attack: 150,
    maxHealth: 200,
    baseExp: 35,
    coreFragments: 800,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 4000,
    scanRate: 60,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 5.6,
    length: 11.8,
    speed: 220,
    type: 'dinosaur',
    weight: 19.9,
    width: 4.4,
  },
  gator_radome: {
    id: 'gator_radome',
    name: 'Gator Radome',
    attack: 150,
    maxHealth: 350,
    baseExp: 45,
    coreFragments: 1500,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 8000,
    scanRate: 50,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 5.6,
    length: 11.8,
    speed: 200,
    type: 'dinosaur',
    weight: 21.5,
    width: 4.4,
  },
  geruder: {
    id: 'geruder',
    name: 'Geruder',
    attack: 160,
    maxHealth: 450,
    baseExp: 50,
    coreFragments: 1400,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.Fluctuating,
    price: 30000,
    scanRate: 30,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    evolutions: [new Evolution('red_horn', new AllOfRule([
      new AttackRule(500),
      new HealthRule(1000),
    ]))],
    height: 4.5,
    length: 10.73,
    speed: 200,
    type: 'dinosaur',
    weight: 25,
  },
  giraffsworder: {
    id: 'giraffsworder',
    name: 'Girafsworder',
    attack: 160,
    maxHealth: 150,
    baseExp: 35,
    coreFragments: 800,
    evolutions: [new Evolution('double_sworder', new AllOfRule([
      new AttackRule(200),
      new HealthRule(200),
    ]))],
    faction: Faction.Neutral,
    levelType: LevelType.Fast,
    price: 5000,
    scanRate: 45,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Land],
    height: 3.6,
    length: 9.2,
    speed: 320,
    type: 'stag_beetle',
    weight: 8.2,
  },
  glidoler: {
    id: 'glidoler',
    name: 'Glidoler',
    attack: 100,
    maxHealth: 40,
    baseExp: 50,
    coreFragments: 1000,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 4000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Air, TerrainType.Land, TerrainType.Water],
    evolutions: [new Evolution('pegasuros', new LevelRule(100))],
    height: 5.2,
    length: 5.3,
    speed: 5186,
    type: 'waterfowl',
    weight: 3.9,
    width: 6.2,
  },
  godos: {
    id: 'godos',
    name: 'Godos',
    attack: 120,
    maxHealth: 250,
    baseExp: 70,
    coreFragments: 1200,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 25000,
    scanRate: -1,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 9,
    length: 12.3,
    speed: 150,
    type: 'dinosaur',
    weight: 23,
    width: 3.8,
  },
  goliath: {
    id: 'goliath',
    name: 'Goliath',
    attack: 10,
    maxHealth: 450,
    baseExp: 60,
    coreFragments: 1000,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 6000,
    scanRate: 80,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Land],
    height: 2.9,
    length: 3.1,
    speed: 120,
    type: 'snail',
    weight: 5,
  },
  gordos: {
    id: 'gordos',
    name: 'Gordos',
    attack: 200,
    maxHealth: 500,
    baseExp: 150,
    coreFragments: 2500,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Slow,
    price: 120000,
    scanRate: -1,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 15.1,
    length: 30.3,
    speed: 80,
    type: 'dinosaur',
    weight: 199,
    width: 9.3,
  },
  gorgodos: {
    id: 'gorgodos',
    name: 'Gorgodos',
    attack: 140,
    maxHealth: 400,
    baseExp: 50,
    coreFragments: 1200,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Slow,
    price: 12000,
    scanRate: 35,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    evolutions: [new Evolution('gordos', new HealthRule(1000))],
    height: 5.2,
    length: 12.2,
    speed: 105,
    type: 'dinosaur',
    weight: 13.3,
    width: 4.4,
  },
  grandmolar: {
    id: 'grandmolar',
    name: 'Grandmolar',
    attack: 120,
    maxHealth: 400,
    baseExp: 50,
    coreFragments: 1000,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumSlow,
    price: 20000,
    scanRate: 40,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Land],
    height: 1.4,
    length: 4.6,
    speed: 90,
    type: 'mole',
    weight: 6.8,
  },
  gunbeetle: {
    id: 'gunbeetle',
    name: 'Gunbeetle',
    attack: 120,
    maxHealth: 200,
    baseExp: 35,
    coreFragments: 800,
    evolutions: [new Evolution('saicurtis', new AllOfRule([
      new AttackRule(200),
      new HealthRule(200),
    ]))],
    faction: Faction.Neutral,
    levelType: LevelType.Fast,
    price: 5000,
    scanRate: 45,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Land],
    height: 3.5,
    length: 8.6,
    speed: 350,
    type: 'beetle',
    weight: 8,
  },
  gurantula: {
    id: 'gurantula',
    name: 'Gurantula',
    attack: 120,
    maxHealth: 300,
    baseExp: 35,
    coreFragments: 800,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 4000,
    scanRate: -1,
    size: ZoidSize.XS,
    terrainTypes: [TerrainType.Land],
    evolutions: [new Evolution('guysack', new AttackRule(100))],
    height: 4.8,
    length: 6,
    speed: 330,
    type: 'spider',
    weight: 4.6,
    width: 6,
  },
  gustav: {
    id: 'gustav',
    name: 'Gustav',
    attack: 0,
    maxHealth: 700,
    baseExp: 80,
    coreFragments: 2500,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Slow,
    price: 1000000,
    scanRate: -1,
    size: ZoidSize.Transport,
    terrainTypes: [TerrainType.Land],
    height: 9.36,
    length: 14.76,
    speed: 135,
    type: 'insect',
    weight: 68,
    width: 8.28,
  },
  gustav_mc: {
    id: 'gustav_mc',
    name: 'Gustav MC',
    attack: 0,
    maxHealth: 800,
    baseExp: 80,
    coreFragments: 2500,
    faction: Faction.Neutral,
    levelType: LevelType.Slow,
    price: 1000000,
    scanRate: -1,
    size: ZoidSize.Transport,
    terrainTypes: [TerrainType.Land],
    height: 9.36,
    length: 14.76,
    speed: 135,
    type: 'insect',
    weight: 68,
    width: 8.28,
  },
  guysack: {
    id: 'guysack',
    name: 'Guysack',
    attack: 170,
    maxHealth: 400,
    baseExp: 45,
    coreFragments: 1200,
    evolutions: [new Evolution('guysack_heavy_armor', new ItemRule('reinforced_cockpit'))],
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 8000,
    scanRate: -1,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    itemDrops: [new ZiDataDrop('gurantula', 30)],
    height: 4,
    length: 10,
    speed: 120,
    type: 'scorpion',
    weight: 22,
    width: 6.2,
  },
  guysack_heavy_armor: {
    id: 'guysack_heavy_armor',
    name: 'Guysack Heavy Armor',
    attack: 180,
    maxHealth: 500,
    baseExp: 50,
    coreFragments: 1200,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 50000,
    scanRate: -1,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    itemDrops: [new ItemDrop('reinforced_cockpit', 20)],
    height: 5,
    length: 12,
    speed: 100,
    type: 'scorpion',
    weight: 30,
    width: 7,
  },
  hammerrock: {
    id: 'hammerrock',
    name: 'Hammerrock',
    attack: 220,
    maxHealth: 450,
    baseExp: 80,
    coreFragments: 1400,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.MediumSlow,
    price: 30000,
    scanRate: 25,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 6.7,
    length: 5.6,
    speed: 180,
    type: 'gorilla',
    weight: 26.8,
    width: 5.9,
  },
  helcat: {
    id: 'helcat',
    name: 'Helcat',
    attack: 160,
    maxHealth: 250,
    baseExp: 50,
    coreFragments: 1400,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 25000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 5,
    length: 13.2,
    speed: 200,
    type: 'panther',
    weight: 24,
    width: 3.8,
  },
  helcat_stray: {
    id: 'helcat_stray',
    name: 'Stray Helcat',
    attack: 200,
    maxHealth: 250,
    baseExp: 70,
    coreFragments: 2000,
    faction: Faction.Neutral,
    levelType: LevelType.MediumFast,
    price: 50000,
    scanRate: 30,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 5,
    length: 13.2,
    speed: 200,
    type: 'panther',
    weight: 24,
    width: 3.8,
  },
  heldigunner: {
    id: 'heldigunner',
    name: 'Heldigunner',
    attack: 200,
    maxHealth: 400,
    baseExp: 70,
    coreFragments: 1600,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 30000,
    scanRate: 35,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 5.8,
    length: 24.5,
    speed: 130,
    type: 'iguana',
    weight: 48,
    width: 6.5,
  },
  helldiver: {
    id: 'helldiver',
    name: 'Helldiver',
    attack: 170,
    maxHealth: 90,
    baseExp: 20,
    coreFragments: 600,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.Fast,
    price: 3000,
    scanRate: 70,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Water],
    height: 2,
    length: 6.6,
    speed: 148,
    type: 'hammerhead_shark',
    weight: 2.9,
  },
  hidocker: {
    id: 'hidocker',
    name: 'Hidocker',
    attack: 90,
    maxHealth: 250,
    baseExp: 50,
    coreFragments: 2500,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumSlow,
    price: 30000,
    scanRate: 30,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 6.8,
    length: 14.2,
    speed: 195,
    type: 'dinosaur',
    weight: 7.9,
    width: 4.2,
  },
  hyperscissors: {
    id: 'hyperscissors',
    name: 'Hyperscissors',
    attack: 40,
    maxHealth: 150,
    baseExp: 20,
    coreFragments: 400,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 2000,
    scanRate: 75,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 1,
    length: 5.8,
    speed: 90,
    type: 'crayfish',
    weight: 3.8,
  },
  iguan: {
    id: 'iguan',
    name: 'Iguan',
    attack: 150,
    maxHealth: 200,
    baseExp: 70,
    coreFragments: 1200,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 25000,
    scanRate: 35,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 8.2,
    length: 10.4,
    speed: 200,
    type: 'dinosaur',
    weight: 23.6,
  },
  iron_kong: {
    id: 'iron_kong',
    name: 'Iron Kong',
    attack: 350,
    maxHealth: 1200,
    baseExp: 200,
    coreFragments: 3000,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.Slow,
    price: 200000,
    scanRate: 10,
    size: ZoidSize.XL,
    terrainTypes: [TerrainType.Land],
    height: 17.7,
    length: 11.5,
    speed: 150,
    type: 'gorilla',
    weight: 187,
    width: 13.1,
  },
  malder: {
    id: 'malder',
    name: 'Malder',
    attack: 20,
    maxHealth: 700,
    baseExp: 70,
    coreFragments: 800,
    evolutions: [new Evolution('gustav', new ItemRule('layered_armor'))],
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.Erratic,
    price: 6000,
    scanRate: 50,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 6.5,
    length: 8.5,
    speed: 120,
    type: 'snail',
    weight: 34.6,
    width: 4.3,
  },
  mammoth: {
    id: 'mammoth',
    name: 'Mammoth',
    attack: 200,
    maxHealth: 700,
    baseExp: 120,
    coreFragments: 2500,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Slow,
    price: 100000,
    scanRate: -1,
    size: ZoidSize.XL,
    terrainTypes: [TerrainType.Land],
    height: 12.2,
    length: 21.6,
    speed: 85,
    type: 'mammoth',
    weight: 145,
    width: 12.9,
  },
  merda: {
    id: 'merda',
    name: 'Merda',
    attack: 50,
    maxHealth: 100,
    baseExp: 20,
    coreFragments: 400,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.Fast,
    price: 2000,
    scanRate: 80,
    size: ZoidSize.XS,
    terrainTypes: [TerrainType.Land],
    height: 6.8,
    length: 12.2,
    speed: 500,
    type: 'dinosaur',
    weight: 17.5,
  },
  missile_tortoise: {
    id: 'missile_tortoise',
    name: 'Missile Tortoise',
    attack: 180,
    maxHealth: 500,
    baseExp: 60,
    coreFragments: 1400,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 15000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 5.9,
    length: 8.7,
    speed: 120,
    type: 'turtle',
    weight: 38.6,
  },
  molga: {
    id: 'molga',
    name: 'Molga',
    attack: 100,
    maxHealth: 400,
    baseExp: 50,
    coreFragments: 1200,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.Fast,
    price: 20000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Land],
    height: 2.95,
    length: 11.8,
    speed: 200,
    type: 'insect',
    weight: 19.7,
    width: 3,
  },
  pegasuros: {
    id: 'pegasuros',
    name: 'Pegasuros',
    attack: 180,
    maxHealth: 100,
    baseExp: 70,
    coreFragments: 1500,
    evolutions: [
      new Evolution('pteras', new AllOfRule([
        new AttackRule(600),
        new FactionRule(Faction.HelicRepublic),
      ])),
      new Evolution('redler', new AllOfRule([
        new AttackRule(600),
        new FactionRule(Faction.GuylosEmpire),
      ])),
    ],
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumSlow,
    price: 30000,
    scanRate: -1,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Air, TerrainType.Land],
    height: 8,
    length: 10,
    speed: 3087,
    type: 'bird',
    weight: 4.7,
    width: 3.2,
  },
  pteras: {
    id: 'pteras',
    name: 'Pteras',
    attack: 180,
    maxHealth: 150,
    baseExp: 70,
    coreFragments: 1200,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 50000,
    scanRate: 50,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Air],
    height: 8.2,
    length: 10.3,
    speed: 2717,
    type: 'pterosaur',
    weight: 21.6,
    width: 16.8,
  },
  red_horn: {
    id: 'red_horn',
    name: 'Red Horn',
    attack: 280,
    maxHealth: 800,
    baseExp: 120,
    coreFragments: 2500,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumSlow,
    price: 150000,
    scanRate: 20,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 7.6,
    length: 20.8,
    speed: 130,
    type: 'styracosaurus',
    weight: 94,
    width: 7.2,
  },
  redler: {
    id: 'redler',
    name: 'Redler',
    attack: 210,
    maxHealth: 150,
    baseExp: 70,
    coreFragments: 1600,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 42000,
    scanRate: 30,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Air],
    height: 6,
    length: 17,
    speed: 3704,
    type: 'dragon',
    weight: 34,
    width: 15,
  },
  saber_tiger: {
    id: 'saber_tiger',
    name: 'Saber Tiger',
    attack: 300,
    maxHealth: 450,
    baseExp: 100,
    coreFragments: 2000,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 100000,
    scanRate: 25,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 9.1,
    length: 15.6,
    speed: 240,
    type: 'tiger',
    weight: 78,
    width: 5.7,
  },
  saber_tiger_gs: {
    id: 'saber_tiger_gs',
    name: 'Saber Tiger GS',
    attack: 350,
    maxHealth: 650,
    baseExp: 150,
    coreFragments: 2500,
    faction: Faction.Neutral,
    levelType: LevelType.MediumSlow,
    price: 160000,
    scanRate: -1,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 9.1,
    length: 15.8,
    speed: 230,
    type: 'tiger',
    weight: 95,
    width: 5.7,
  },
  saber_tiger_rs: {
    id: 'saber_tiger_rs',
    name: 'Saber Tiger RS',
    attack: 320,
    maxHealth: 500,
    baseExp: 150,
    coreFragments: 2500,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.MediumFast,
    price: 150000,
    scanRate: -1,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 9.1,
    length: 15.6,
    speed: 240,
    type: 'tiger',
    weight: 78,
    width: 5.7,
  },
  saicurtis: {
    id: 'saicurtis',
    name: 'Saicurtis',
    attack: 160,
    maxHealth: 220,
    baseExp: 50,
    coreFragments: 1000,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.Fast,
    price: 35000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Air, TerrainType.Land],
    height: 3.7,
    length: 11.9,
    speed: 390,
    type: 'beetle',
    weight: 17.4,
    width: 11.2,
  },
  saradin: {
    id: 'saradin',
    name: 'Saradin',
    attack: 60,
    maxHealth: 500,
    baseExp: 50,
    coreFragments: 1000,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumSlow,
    price: 10000,
    scanRate: 60,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Land],
    height: 1.8,
    length: 5.5,
    speed: 120,
    type: 'armadillo',
    weight: 6.5,
  },
  sea_batoras: {
    id: 'sea_batoras',
    name: 'Sea Batoras',
    attack: 50,
    maxHealth: 180,
    baseExp: 20,
    coreFragments: 400,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 2500,
    scanRate: 70,
    size: ZoidSize.XXS,
    terrainTypes: [TerrainType.Water],
    height: 0.9,
    length: 4.5,
    speed: 750,
    type: 'horseshoe_crab',
    weight: 4.9,
  },
  sea_panther: {
    id: 'sea_panther',
    name: 'Sea Panther',
    attack: 90,
    maxHealth: 400,
    baseExp: 50,
    coreFragments: 1400,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.MediumSlow,
    price: 8000,
    scanRate: 40,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Water, TerrainType.Land],
    height: 4.9,
    length: 9,
    speed: 93,
    type: 'hermit_crab',
    weight: 28.5,
    width: 5.4,
  },
  shield_liger: {
    id: 'shield_liger',
    name: 'Shield Liger',
    attack: 250,
    maxHealth: 600,
    baseExp: 100,
    coreFragments: 2000,
    faction: Faction.HelicRepublic,
    levelType: LevelType.MediumFast,
    price: 100000,
    scanRate: 25,
    size: ZoidSize.L,
    terrainTypes: [TerrainType.Land],
    height: 9,
    length: 21.6,
    speed: 250,
    type: 'lion',
    weight: 92,
    width: 6,
  },
  sinker: {
    id: 'sinker',
    name: 'Sinker',
    attack: 180,
    maxHealth: 120,
    baseExp: 40,
    coreFragments: 1200,
    faction: Faction.GuylosEmpire,
    levelType: LevelType.Fast,
    price: 20000,
    scanRate: 40,
    size: ZoidSize.S,
    terrainTypes: [TerrainType.Air, TerrainType.Water],
    height: 3,
    length: 10.8,
    speed: 111,
    type: 'stingray',
    weight: 26.6,
    width: 12.7,
  },
  spiker: {
    id: 'spiker',
    name: 'Spiker',
    attack: 150,
    maxHealth: 180,
    baseExp: 35,
    coreFragments: 800,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 5000,
    scanRate: 55,
    size: ZoidSize.XS,
    terrainTypes: [TerrainType.Land],
    height: 6,
    length: 9,
    speed: 220,
    type: 'mantis',
    weight: 6.4,
    width: 4.2,
  },
  stealth_viper: {
    id: 'stealth_viper',
    name: 'Stealth Viper',
    attack: 180,
    maxHealth: 200,
    baseExp: 45,
    coreFragments: 1600,
    faction: Faction.HelicRepublic,
    levelType: LevelType.Fast,
    price: 25000,
    scanRate: 40,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 3,
    length: 20.8,
    speed: 180,
    type: 'snake',
    weight: 23.6,
    width: 4.2,
  },
  twinhorn: {
    id: 'twinhorn',
    name: 'Twinhorn',
    attack: 180,
    maxHealth: 500,
    baseExp: 80,
    coreFragments: 2000,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.MediumSlow,
    price: 100000,
    scanRate: 20,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 8.4,
    length: 9.1,
    speed: 180,
    type: 'mammoth',
    weight: 25.3,
    width: 4.5,
  },
  zatton: {
    id: 'zatton',
    name: 'Zatton',
    attack: 120,
    maxHealth: 350,
    baseExp: 40,
    coreFragments: 1000,
    faction: Faction.ZenebasEmpire,
    levelType: LevelType.MediumSlow,
    price: 10000,
    scanRate: 40,
    size: ZoidSize.M,
    terrainTypes: [TerrainType.Land],
    height: 8.7,
    length: 10.1,
    speed: 180,
    type: 'dinosaur',
    weight: 25.5,
    width: 4,
  },
};
